//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rectify.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetail
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int HoursPerDay { get; set; }
        public System.DateTime AttendanceDate { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
