//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rectify.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttendanceMaster()
        {
            this.AttendanceDetails = new HashSet<AttendanceDetail>();
        }
    
        public int MasterID { get; set; }
        public int MentorID { get; set; }
        public string TrainedOn { get; set; }
        public System.DateTime AttendanceDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceDetail> AttendanceDetails { get; set; }
        public virtual Person Person { get; set; }
    }
}
