//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rectify.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetail
    {
        public int DetailID { get; set; }
        public int PersonID { get; set; }
        public int MasterID { get; set; }
        public decimal HoursPerDay { get; set; }
    
        public virtual AttendanceMaster AttendanceMaster { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
